version: '3.8'

services:
  sentiment-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./:/app
    working_dir: /app